// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: twomemo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// OMEMO 2 wire format, XEP-0384 v0.9.x §"Protobuf Schema".

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Twomemo_OMEMOMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var n: UInt32 {
    get {_n ?? 0}
    set {_n = newValue}
  }
  /// Returns true if `n` has been explicitly set.
  var hasN: Bool {self._n != nil}
  /// Clears the value of `n`. Subsequent reads from it will return its default value.
  mutating func clearN() {self._n = nil}

  var pn: UInt32 {
    get {_pn ?? 0}
    set {_pn = newValue}
  }
  /// Returns true if `pn` has been explicitly set.
  var hasPn: Bool {self._pn != nil}
  /// Clears the value of `pn`. Subsequent reads from it will return its default value.
  mutating func clearPn() {self._pn = nil}

  var dhPub: Data {
    get {_dhPub ?? Data()}
    set {_dhPub = newValue}
  }
  /// Returns true if `dhPub` has been explicitly set.
  var hasDhPub: Bool {self._dhPub != nil}
  /// Clears the value of `dhPub`. Subsequent reads from it will return its default value.
  mutating func clearDhPub() {self._dhPub = nil}

  var ciphertext: Data {
    get {_ciphertext ?? Data()}
    set {_ciphertext = newValue}
  }
  /// Returns true if `ciphertext` has been explicitly set.
  var hasCiphertext: Bool {self._ciphertext != nil}
  /// Clears the value of `ciphertext`. Subsequent reads from it will return its default value.
  mutating func clearCiphertext() {self._ciphertext = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _n: UInt32? = nil
  fileprivate var _pn: UInt32? = nil
  fileprivate var _dhPub: Data? = nil
  fileprivate var _ciphertext: Data? = nil
}

nonisolated struct Twomemo_OMEMOAuthenticatedMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var mac: Data {
    get {_mac ?? Data()}
    set {_mac = newValue}
  }
  /// Returns true if `mac` has been explicitly set.
  var hasMac: Bool {self._mac != nil}
  /// Clears the value of `mac`. Subsequent reads from it will return its default value.
  mutating func clearMac() {self._mac = nil}

  /// Byte-encoding of an OMEMOMessage
  var message: Data {
    get {_message ?? Data()}
    set {_message = newValue}
  }
  /// Returns true if `message` has been explicitly set.
  var hasMessage: Bool {self._message != nil}
  /// Clears the value of `message`. Subsequent reads from it will return its default value.
  mutating func clearMessage() {self._message = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _mac: Data? = nil
  fileprivate var _message: Data? = nil
}

nonisolated struct Twomemo_OMEMOKeyExchange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pkID: UInt32 {
    get {_pkID ?? 0}
    set {_pkID = newValue}
  }
  /// Returns true if `pkID` has been explicitly set.
  var hasPkID: Bool {self._pkID != nil}
  /// Clears the value of `pkID`. Subsequent reads from it will return its default value.
  mutating func clearPkID() {self._pkID = nil}

  var spkID: UInt32 {
    get {_spkID ?? 0}
    set {_spkID = newValue}
  }
  /// Returns true if `spkID` has been explicitly set.
  var hasSpkID: Bool {self._spkID != nil}
  /// Clears the value of `spkID`. Subsequent reads from it will return its default value.
  mutating func clearSpkID() {self._spkID = nil}

  var ik: Data {
    get {_ik ?? Data()}
    set {_ik = newValue}
  }
  /// Returns true if `ik` has been explicitly set.
  var hasIk: Bool {self._ik != nil}
  /// Clears the value of `ik`. Subsequent reads from it will return its default value.
  mutating func clearIk() {self._ik = nil}

  var ek: Data {
    get {_ek ?? Data()}
    set {_ek = newValue}
  }
  /// Returns true if `ek` has been explicitly set.
  var hasEk: Bool {self._ek != nil}
  /// Clears the value of `ek`. Subsequent reads from it will return its default value.
  mutating func clearEk() {self._ek = nil}

  var message: Twomemo_OMEMOAuthenticatedMessage {
    get {_message ?? Twomemo_OMEMOAuthenticatedMessage()}
    set {_message = newValue}
  }
  /// Returns true if `message` has been explicitly set.
  var hasMessage: Bool {self._message != nil}
  /// Clears the value of `message`. Subsequent reads from it will return its default value.
  mutating func clearMessage() {self._message = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _pkID: UInt32? = nil
  fileprivate var _spkID: UInt32? = nil
  fileprivate var _ik: Data? = nil
  fileprivate var _ek: Data? = nil
  fileprivate var _message: Twomemo_OMEMOAuthenticatedMessage? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "twomemo"

nonisolated extension Twomemo_OMEMOMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OMEMOMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}n\0\u{1}pn\0\u{3}dh_pub\0\u{1}ciphertext\0")

  public var isInitialized: Bool {
    if self._n == nil {return false}
    if self._pn == nil {return false}
    if self._dhPub == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._n) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._pn) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._dhPub) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self._ciphertext) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._n {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._pn {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._dhPub {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._ciphertext {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Twomemo_OMEMOMessage, rhs: Twomemo_OMEMOMessage) -> Bool {
    if lhs._n != rhs._n {return false}
    if lhs._pn != rhs._pn {return false}
    if lhs._dhPub != rhs._dhPub {return false}
    if lhs._ciphertext != rhs._ciphertext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Twomemo_OMEMOAuthenticatedMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OMEMOAuthenticatedMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mac\0\u{1}message\0")

  public var isInitialized: Bool {
    if self._mac == nil {return false}
    if self._message == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._mac) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._mac {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._message {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Twomemo_OMEMOAuthenticatedMessage, rhs: Twomemo_OMEMOAuthenticatedMessage) -> Bool {
    if lhs._mac != rhs._mac {return false}
    if lhs._message != rhs._message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Twomemo_OMEMOKeyExchange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OMEMOKeyExchange"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}pk_id\0\u{3}spk_id\0\u{1}ik\0\u{1}ek\0\u{1}message\0")

  public var isInitialized: Bool {
    if self._pkID == nil {return false}
    if self._spkID == nil {return false}
    if self._ik == nil {return false}
    if self._ek == nil {return false}
    if self._message == nil {return false}
    if let v = self._message, !v.isInitialized {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._pkID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._spkID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._ik) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self._ek) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._pkID {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._spkID {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._ik {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._ek {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._message {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Twomemo_OMEMOKeyExchange, rhs: Twomemo_OMEMOKeyExchange) -> Bool {
    if lhs._pkID != rhs._pkID {return false}
    if lhs._spkID != rhs._spkID {return false}
    if lhs._ik != rhs._ik {return false}
    if lhs._ek != rhs._ek {return false}
    if lhs._message != rhs._message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
